# Generated by Django 4.1.5 on 2023-02-08 01:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/default/user/default_avatar.jpg', upload_to=users.models.photo_up_path),
        ),
    ]
